#pragma once

int main_00_HelloWorld();
int main_01_PrintingText();
int main_02_IOStreams();
int main_03_Namespaces();
int main_04_Literals();
int main_05_Variables();
int main_06_Limits();
int main_07_ZeroInitialization();
int main_08_Casting();
int main_09_FloatingPoint();
int main_10_Enumerations();
int main_11_Structs();
int main_12_ConditionalStatements();
int main_13_ThreeWayComparisons();
int main_14_Functions();
int main_15_Attributes();
int main_16_Arrays();
int main_17_vector();
int main_18_optional();
int main_19_StructuredBindings();
int main_20_Loops();
int main_21_InitializerLists();
int main_22_Strings();
int main_23_UniformInitialization();
int main_24_DesignatedInitializers();
int main_25_Exceptions();